apiVersion: v1
kind: Service
metadata: 
  name: list-alerts
spec:
  selector:
    app: list-alerts
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 8080
      
    
